language: java

jdk:
  - oraclejdk8
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - oracle-java8-installer

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master